[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # Samakan penamaan agar konsisten dengan config.js
  VITE_PUBLIC_VAPID_KEY = "${VAPID_PUBLIC_KEY}"
  PUSH_SERVER_URL = "https://your-push-server.example" # ganti sesuai servermu

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200